### ISSUE TITLE
Apollo LEM crashes the game when using OpenGL

### ISSUE THREAD

**Issue by arrowmaster** [KSP-RO/ROCapsules#116]
Adding the Apollo LEM to a craft in the VAB will cause a constant spam of `OpenGL Error: Invalid texture unit!` to Player.log and soon crash the game. Nothing unusual is reported in KSP.log.

**Comment by JonSeverinsson** [comment]
I'm hitting what I think is the same bug*, and it affects not only the LEM (`Apollo LM Ascent Stage` & `Apollo LM Descent Stage`), but also the `Apollo Lunar Roving Vehicle (LRV)` and `Apollo Drogue Docking Port`. The LEM and LRV isn't really a problem for me, I can build a different lunar lander if I have to, but the `Apollo Drogue Docking Port` is **essential**, as it is the **only** part the `Apollo CM Forward Heat Shield` will mate with...

*: I'm on Linux, so OpenGL is the only option, and while KSP doesn't crash for me, I am get the same "`OpenGL Error: Invalid texture unit!`" message in Player.log. As Player.log grows to exceed about 5 GiB my DE will minimizes KSP in order to tell me that I'm running out of disk space in my home directory. At that point the only way to stop it from continuing to nag me every time Player.log grows another 4 kiB is to close KSP, remove Player.log, and start KSP again. (I suspect that KSP would crash if I let Player.log grow to completely fill the disk, but I'm not about to continue to dismiss 41943 warnings just to find out...)

**Comment by arrowmaster** [comment]
I keep offering bribes on Discord for getting the new BDB Apollo models in ROC but nobody has taken up the offer yet.

@JonSeverinsson For work arounds to your problems, have you tried the D-2 Apollo Drogue Docking port? Another option is deleting the contents of Player.log without restarting KSP. If you delete the file KSP will still have it open and continue using it until KSP is closed but if you do `echo "" > Player.log` it will replace the entire contents of the file with nothing and should free up your disk space.

**Comment by JonSeverinsson** [comment]
@arrowmaster: I have, the `D-2 Docking Drogue` does not mate to the `Apollo CM Forward Heat Shield`.

My current workaround is to ignore the docking port in the `Apollo CM Forward Heat Shield`, using it only as a heat shield and parachute cover, and stick an androgynous `Apollo Docking System` docking port (the stock docking port, renamed by RO) on top of it, and another one on my space station. It looks ugly as hell, and the docking probe from the heat shield docking port clips through the androgynous docking port, but it doesn't block mating, so it works...

**Comment by Capkirk123** [comment]
> I keep offering bribes on Discord for getting the new BDB Apollo models in ROC but nobody has taken up the offer yet.

Hey, I'll do it for an NTK 24305.

**Comment by vader111** [comment]
> I keep offering bribes on Discord for getting the new BDB Apollo models in ROC but nobody has taken up the offer yet.

$200 USD and I will have it done in 5 days.

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROCapsules/pull/132
