### ISSUE TITLE
Vostok overheat

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ROCapsules#90]
I have been unable to successfully reenter with a Vostok capsule. From a nominal orbit with an apogee of 300km or less, and a post-retro periapsis between 40km and -250km, the result is always an overheat and explosion. All mods are either release or master as of around 6/7/21

**Comment by NathanKell** [comment]
Tried it with dev RO (i.e. including MeanerHeating changes) and KSP-RO's version of Deadly Reentry. Survived a 300x300 reentry (with a ~148m/s retrofire, so probably 300x-200 descent orbit, I didn't check) from 50 degrees inclination.  28.45 ablator left, which is a bit worryingly low. Also had the temp gauge show up, but it never poofed.

Seems like maybe it needs a bit better heatshielding, but otherwise is fine. You're probably getting poofed by DRE, so uninstall that.

**Comment by NathanKell** [comment]
Assuming you are on dev of RO, and get MeanerHeating of ROCapsules, should be better. Closing for now.

**Comment by NathanKell** [comment]
Was fine with high entry angle (>3deg). Ran out of ablator and blew up from 150m/s retrofire at perigee (from 327x189km orbit). Need to increase ablator supply. Incidentally our capsule is too heavy, seems it should be ~2.5t total and ours is 2.7t, which doesn't help.

**Comment by NathanKell** [comment]
Closed by d8d5bf7f0621f59857da9edd0a0b310f19b856c5

**Comment by siimav** [comment]
Now I wonder if Nathan did the changes with MeanerHeating enabled or disabled...

**Comment by Capkirk123** [comment]
Vostok/Voskhod will survive both extremely shallow (300x100) and extremely steep (300x-150) reentries, although it will get a little close to ablator depletion on the shallow end, and awful close to the max temp on the steep end.
This seems acceptable, Vostok had generally better margins than Mercury and was designed to survive a passive orbital decay in the event of deorbit motor failure.
