### ISSUE TITLE
Heat shields should have their ModuleAblators re-added

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ROCapsules#91]
The original parts we use often had char animations. Those should be re-added.

**Comment by Capkirk123** [comment]
Looking through the parts we have
BDB Apollo: No char animation on original part
CST-100: No char animation on original part
Dynasoar: N/A
BDB Gemini: No char animation on original part
BDB Mercury: No char animation on the original part
DECQ Orion: No char animation on the original part?
RN Vostok/Voskhod: No char animation on the original part

For better or worse, there are currently no parts in ROCapsules that had a char animation on the first place, so this issue is no longer applicable
